[build]
  publish = "public"
  command = "npm run build"
[build.environment]
  NODE_VERSION = "16.13.1"
  YARN_VERSION = "1.22.4"
  YARN_FLAGS = "--no-ignore-optional"
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=360000"

