backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

media_folder: static/img
public_folder: /img

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/pages/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Featured Post", name: "featuredpost", widget: "boolean"}
      - {label: "Featured Image", name: "featuredimage", widget: image}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list"}
  - name: "work"
    label: "Work"
    folder: "src/pages/work"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "work-post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Featured Post", name: "featuredpost", widget: "boolean"}
      - {label: "Work Date", name: "workdate", widget: "string"}
      - {label: "Featured Image", name: "featuredimage", widget: image}
      - {label: "Card Image", name: "cardimage", widget: image }
      - {label: "Card Background Color", name: "cardcolor", widget: "string"}
      - {label: "Summary", name: "summary", widget: "markdown"}
      - {label: "Roles", name: "roles", widget: "markdown"}
      - {label: "Showcase Image", name: "showcase1", widget: object, required: false, fields: [{label: "Background Image", name: "backgroundimage", widget: image}, {label: "Height", name: "height", widget: number}, {label: "Fixed", name: "fixed", default: false, widget: "boolean"}]}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Showcase Image", name: "showcase2", widget: object, required: false, fields: [{label: "Background Image", name: "backgroundimage", widget: image}, {label: "Height", name: "height", widget: number}, {label: "Fixed", name: "fixed", default: false, widget: "boolean"}]}
      - {label: "Learning", name: "learning", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list"}
  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/index.md"
        label: "Landing Page"
        name: "index"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "index-page"}
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: Subheading, name: subheading, widget: string}
      - file: "src/pages/about/index.md"
        label: "About"
        name: "about"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
      
